# This file is used by the Thunderstore CLI to build and publish your mod to Thunderstore. https://github.com/thunderstore-io/thunderstore-cli

[config]
schemaVersion = "0.0.1"

[package]
namespace = "nullobsi" # TODO: Change this to the team you're uploading the mod to on Thunderstore
name = "FixHandPose" # Change this to your mod's name, no spaces or special characters, max 128 characters
# versionNumber = "1.0.0" # Uncomment this if publishing via manual tcli! Change this to your mod's version, must be in semantic versioning format (e.g. 1.0.0, 2.1.3, 0.1.0-alpha.1)
description = "Fix hand pose for SteamVR drivers missing skeletal input" # TODO: Change this to your mod's description, max 250 characters
websiteUrl = "https://github.com/nullobsi/FixHandPose" # TODO: Change this to your mod's website/repository, or leave blank
containsNsfwContent = false

# List any dependencies your mod has here, in the format "namespace-modname" = "version-constraint"
[package.dependencies] 
ResoniteModding-BepisLoader = "1.6.0"
ResoniteModding-BepisResoniteWrapper = "1.0.2"
ResoniteModding-BepInExRenderer = "5.4.233001"
ResoniteModding-RenderiteHook = "1.1.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

# Copy the compiled DLL to the plugins folder in the mod package
[[build.copy]]
source = "./FixHandPose.FrooxEngine/bin/Release/FixHandPose.FrooxEngine.dll"
target = "plugins/FixHandPose.FrooxEngine/"

# Include the PDB file for better debugging support
[[build.copy]]
source = "./FixHandPose.FrooxEngine/bin/Release/FixHandPose.FrooxEngine.pdb"
target = "plugins/FixHandPose.FrooxEngine/"

# Copy the compiled DLL to the plugins folder in the mod package
[[build.copy]]
source = "./FixHandPose.Unity/bin/Release/FixHandPose.Unity.dll"
target = "Renderer/BepInEx/plugins/FixHandPose.Unity/"

# Include the PDB file for better debugging support
[[build.copy]]
source = "./FixHandPose.Unity/bin/Release/FixHandPose.Unity.pdb"
target = "Renderer/BepInEx/plugins/FixHandPose.Unity/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[[build.copy]]
source = "./LICENSE"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["resonite"]

[publish.categories]
resonite = [ "mods" ] # TODO: Change this to your mod's categories, see https://thunderstore.io/api/experimental/community/resonite/category/ for a list of available categories
