<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>1.0.1</Version>
    <Authors>nullobsi</Authors>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>12</LangVersion>
    <RepositoryUrl>https://github.com/nullobsi/FixHandPose</RepositoryUrl>
    <PackageId>dog.unix.FixHandPose.Unity</PackageId>
    <Product>FixHandPose (for Unity)</Product>
    <RootNamespace>FixHandPose.Unity</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Deterministic>true</Deterministic>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyToPlugins>false</CopyToPlugins>
    <ThunderstorePackable>true</ThunderstorePackable>
    <GamePath Condition="'$(ResonitePath)' != ''">$(ResonitePath)/</GamePath>
    <GamePath Condition="Exists('$(MSBuildProgramFiles32)\Steam\steamapps\common\Resonite\')">$(MSBuildProgramFiles32)\Steam\steamapps\common\Resonite\</GamePath>
    <GamePath Condition="Exists('$(HOME)/.steam/steam/steamapps/common/Resonite/')">$(HOME)/.steam/steam/steamapps/common/Resonite/</GamePath>
    <PluginTargetDir>$(GamePath)Renderer\BepInEx\plugins\$(AssemblyName)</PluginTargetDir>
    <RestoreAdditionalProjectSources>
      https://nuget-modding.resonite.net/v3/index.json;
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
      https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
  </PropertyGroup>

  <!-- Modding dependencies -->
  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all"/>
    <!-- Add this for BepInEx 6
    <PackageReference Include="BepInEx.Unity.Mono" Version="6.0.0-be.*" IncludeAssets="compile" />
	-->
    <PackageReference Include="BepInEx.Core" Version="5.*"/>
    <PackageReference Include="UnityEngine.Modules" Version="2019.4.19" IncludeAssets="compile"/>
  </ItemGroup>

  <!-- Local game references -->
  <ItemGroup Condition="Exists('$(GamePath)')">
    <Reference Include="Renderite.Shared">
      <HintPath>$(GamePath)Renderer/Renderite.Renderer_Data/Managed/Renderite.Shared.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <!-- Post-build copy to game plugins folder -->
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <ItemGroup>
      <PluginFiles Include="$(TargetPath)"/>
      <PluginFiles Include="$(TargetDir)$(TargetName).pdb" Condition="Exists('$(TargetDir)$(TargetName).pdb')"/>
    </ItemGroup>
    <Copy SourceFiles="@(PluginFiles)" DestinationFolder="$(PluginTargetDir)" Condition="'$(CopyToPlugins)' == 'true'"/>
    <Message Text="Copied plugin files to $(PluginTargetDir)" Importance="high" Condition="'$(CopyToPlugins)' == 'true'"/>
  </Target>

  <!-- Include shared patch to Renderite.Shared -->
  <ItemGroup>
    <Compile Include="../FixHandPose.Shared/**/*.cs"/>
  </ItemGroup>
</Project>
